<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Movie;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCountByMovie(Movie $movie): int
    {
        return $this->createQueryBuilder('r')
            ->select('count(r.id)')
            ->andWhere('r.movie = :movie')
            ->setParameter('movie', $movie)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
